-- 1. backend_dev (Role: CRUD semua table di skema SALAM)
CREATE USER backend_dev WITH PASSWORD 'dev_password';
GRANT USAGE ON SCHEMA SALAM TO backend_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

-- 2. bi_dev (Role: Hanya read/select semua table/view di skema SALAM)
CREATE USER bi_dev WITH PASSWORD 'bi_password';
GRANT USAGE ON SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT SELECT ON TABLES TO bi_dev;

-- 3. data_engineer (Role: CREATE, MODIFY, DROP semua objects, CRUD semua table di skema SALAM)
CREATE USER data_engineer WITH PASSWORD 'de_password';
GRANT CREATE ON SCHEMA SALAM TO data_engineer;
GRANT USAGE ON SCHEMA SALAM TO data_engineer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
ALTER SCHEMA SALAM OWNER TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO data_engineer;